### ISSUE TITLE
Solidity ABI annotations and modifiers.

### ISSUE THREAD

**Issue by androlo** [eris-ltd/decerver#104]
This is a spec for doing post processing of json abi data from javascript, in order to set the javascript contract objects up correctly. Some of the problems right now is you need to choose manually if a method should be done using `call` or `transact`. Nor is there any reliable way of finding out whether a method changes the world state or not. Even if the compiler tried to figure it out, it would fail in such instances where the contract makes a generic call to another contract.

Another case in which this is useful is when you want to cut methods out of an abi json file because they simply have no use - even if the methods are in fact callable. An example of this is methods that may only be called by other contracts (or maybe just one specific contract account), due to how the permissions are set up.

The point is not to affect the actual generation of the ABI done by the solidity compiler, only to do post processing of the js object that is generated from it.

Also, this could of course be put in a separate file. That would reduce the amount of clutter in the Solidity contracts. I like the idea of making both things possible - both source file annotations and an external file. For example, the auto deployer could look for a modifiers.json or something in the contract folder, and unless one is found it would read from contract source files. The reason is because modifiers would not often be needed, so wouldn't add too much stuff, so it might be more convenient just to put it in the source files where it is needed.

**Annotations**

Annotations would be added to contract sources inside of comments, so it does not mess with the Solidity compiler. The notation I suggest is this:

```
$$ABI_MODIFIER$$
```

In order to not re-invent the wheel, `ABI_MODIFIER` is just a json string that looks like this:

```
{
    "name" : String (name of method)
    "type" : String (type of modifier, 'accessor', 'exported', 'return_json', ...)
    "value" : depends on the type
}
```

Example:

```
  // $${"name" : "send", "type" : "exported", "value" : false }$$
  /// @notice Send `(valueInmGAV / 1000).fixed(0,3)` GAV from the account of 
  /// `message.caller.address()`, to an account accessible only by `to.address()
  /// @dev This should be the documentation of the function for the developer docs
  /// @param to The address of the recipient of the GavCoin
  /// @param valueInmGav The GavCoin value to send
  function send(address to, uint256 valueInmGAV) {
    if (balances[message.caller] >= valueInmGAV) {
      balances[to] += valueInmGAV;
      balances[message.caller] -= valueInmGAV;
    }
```

By including the name in the annotation, we avoid excessive parsing of the source code. This means also that the annotations could be put anywhere in the source, but i believe personally that they should be put either above the relevant method/field, or in a group right above the contract along with the description and natspec.

Note that automatically generated accessor functions will have the same name as their fields, so unless the "grouping strategy" is used, they would be put at the corresponding field.

As alternatives to the above notation, I would also suggest adding an array form for the types, meaning this would also be allowed:

```
{
    "name" : String (name of method)
    "modifiers" : [{"type" : sometype, "value" : somevalue]}, ...]
}
```

Notice that since it's only json, this is how it could be done in a group:

```
$$
[
{
    "name" : somename,
    "type" : sometype,
    "value" : somevalue
},{
    "name" : someothername
    "modifiers" : [...]
} , ... 
]
$$
```

**Types**

These are the type of modification i feel would be useful. Json formatted to make it possible to use in tooltips and whatnot :D

``` javascript
{
    "name" : "accessor",
    "value_type" : "boolean",
    "default_value" : false,
    "description" : "Makes sure the method uses `call`."
}
```

``` javascript
{
    "name" : "exported",
    "value_type" : "boolean",
    "default_value" : true,
    "description" : "If this is disabled, the method will be removed from the ABI"
}
```

``` javascript
{
    "name" : "returns_json",
    "value_type" : "boolean",
    "default_value" : false,
    "description" : "If checked it will add an interceptor to the javascript contract method that takes the output (normally an array) and turns it into an object where the name of each value is that which is specified in the ABIs 'outputs' array"
}
```

**Processing**

When the data is read, it would match names and put all of them into an array containing one `{name,types[] }` object for each name it finds. It would then use those to go over the regular ABI and complement it with the following fields:

`"accessor" : bool`
`"exported": bool`
`"returns_json" : bool`

This is then used when creating the contract object. Of course, if `exported` is set to `false`, the function could just be removed, and no modifier is needed, although for the sake of completeness I would like to keep it in the ABI. This means they could still be used as normal by web3 etc.

**Comment by androlo** [comment]
Got it working. The Solidity compiler creates a json interface automatically, but there is currently no way to get it from the eth rpc server. This is not an issue, though. Hopefully it will be added to the return of a Solidity compile call, and even web3, but until then it can be gotten straight from the compiler (guessing we'll use the second approach as we do solidity compilation from solc rather then cpp-eth). Probably just going to continue adding abi json files for now, as that's the most reliable and simple way.

I have commented it and done all of that stuff. I also have the auto deployer/txr/tester working + much of the code for the contract generator that wraps web3 contracts but makes use of all these new abi features. Will finalize and add the tests later. Want to get the webpage and stuff working.

Modifiers object:
```
var modTypes = {
    "accessor" : {
        "name" : "accessor",
        "value_type" : "boolean",
        "default_value" : false,
        "description" : "Makes sure the method uses `call`."
    },
    "exported" : {
        "name" : "exported",
        "value_type" : "boolean",
        "default_value" : true,
        "description" : "If this is disabled, the method will be removed from the ABI"
    },
    "returns_json" : {
        "name" : "returns_json",
        "value_type" : "boolean",
        "default_value" : false,
        "description" : "If checked it will add an interceptor to the javascript contract method that takes the output (normally an array) and turns it into an object where the name of each value is that which is specified in the ABIs 'outputs' array"
    }
};
```
Annotations (not including super contracts):
```
// The doug contract. Extend the db for now. Don't want to make things too weird.
contract Doug is DougDb {

	address owner;
	
    // Constructor
    function Doug(){
        owner = msg.sender;
    }

    // $$
    // {
    //      "name" : "addContract",
    //      "type" : "returns_json",
    //      "value": true
    // }
    // $$
    // $$
    // {
    //      "name" : "addContract",
    //      "modifiers" : [{"type" : "exported", "value": false}]
    // }
    // $$
    // $$
    // [{
    //      "name" : "addContract",
    //      "modifiers" : [{"type" : "accessor",
    //      "value": true}]
    // }]
    // $$
    //
    // Add a new contract to Doug. This will overwrite an existing contract.
    function addContract(string32 name, address addr) constant returns (bool result) {
        if(msg.sender != owner){
            return false;
        }
        return _addElement(name, addr);
    }

    // Remove a contract from Doug. We could also suicide if we want to.
    function removeContract(string32 name) constant returns (bool result) {
        if(msg.sender != owner){
            return false;
        }
        return _removeElement(name);
    }
    
    function contracts(string32 name) returns (address addr){
    	return list[name].contractAddress;
    }

    function remove(){
        if(msg.sender == owner){
            // Finally, remove doug. Doug will now have all the funds of the other contracts, 
            // and when suiciding it will all go to the owner.
            suicide(owner);
        }
    }

}
```
Output (addContract is furthest down)
```
/usr/local/bin/node abi_generator.js
Generating new ABI
Parsing source code. Length: 3711
Source file parsed.
Mods array: 
[ { name: 'addContract', type: 'returns_json', value: true },
  { name: 'addContract', modifiers: [ [Object] ] },
  { name: 'addContract', modifiers: [ [Object] ] } ]
Mods object created.
{ addContract: 
   [ { type: 'returns_json', value: true },
     { type: 'exported', value: false },
     { type: 'accessor', value: true } ] }
Applying modifications to current ABI
Found mod for 'addContract': (returns_json, true)
Found mod for 'addContract': (exported, false)
Found mod for 'addContract': (accessor, true)
Generated ABI:
[ { constant: true,
    inputs: [],
    name: 'tail',
    outputs: [ [Object] ],
    type: 'function',
    accessor: false,
    exported: true,
    returns_json: false },
  { constant: true,
    inputs: [ [Object] ],
    name: 'removeContract',
    outputs: [ [Object] ],
    type: 'function',
    accessor: false,
    exported: true,
    returns_json: false },
  { constant: true,
    inputs: [],
    name: 'head',
    outputs: [ [Object] ],
    type: 'function',
    accessor: false,
    exported: true,
    returns_json: false },
  { constant: true,
    inputs: [],
    name: 'size',
    outputs: [ [Object] ],
    type: 'function',
    accessor: false,
    exported: true,
    returns_json: false },
  { constant: false,
    inputs: [],
    name: 'remove',
    outputs: [],
    type: 'function',
    accessor: false,
    exported: true,
    returns_json: false },
  { constant: true,
    inputs: [ [Object] ],
    name: 'getElement',
    outputs: [ [Object], [Object], [Object], [Object] ],
    type: 'function',
    accessor: false,
    exported: true,
    returns_json: false },
  { constant: false,
    inputs: [ [Object] ],
    name: 'contracts',
    outputs: [ [Object] ],
    type: 'function',
    accessor: false,
    exported: true,
    returns_json: false },
  { constant: true,
    inputs: [ [Object], [Object] ],
    name: 'addContract',
    outputs: [ [Object] ],
    type: 'function',
    returns_json: true,
    exported: false,
    accessor: true } ]

Process finished with exit code 0
```

**Comment by compleatang** [comment]
@androlo this is tremendous, but as with #105 can we move to decerver-node?
