### ISSUE TITLE
clang error issues : linker command failed with exit code 1

### ISSUE THREAD

**Issue by rajatmohanty** [eris-ltd/decerver#108]
I am using Mac OS X (Yosemite) & i have successfully installed

1)Go SDK
2)Homebrew
3)GMP -> brew install gmp 
4)Mercurial
5)cURL
6)Xcode 6.1

After that i set my GOPATH

$ mkdir $HOME/gocode
$ export GOPATH=$HOME/gocode
$ export PATH=$PATH:$GOPATH/bin

Then i tried 

$ go get github.com/eris-ltd/decerver
$ cd $GOPATH/src/github.com/eris-ltd/decerver/cmd/decerver/
$ go get -d
$ go install

But now i am getting an error in my terminal, Can you please help me to fix this ?

github.com/eris-ltd/thelonious/Godeps/_workspace/src/github.com/obscuren/secp256k1-go
ld: warning: ignoring file /usr/local/lib/libgmp.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libgmp.dylib
Undefined symbols for architecture i386:
  "___gmpn_add_n", referenced from:
      _secp256k1_num_subadd in secp256.cgo2.o
  "___gmpn_copyi", referenced from:
      _secp256k1_ecmult in secp256.cgo2.o
      _secp256k1_num_mul in secp256.cgo2.o
      _secp256k1_num_div in secp256.cgo2.o
  "___gmpn_gcdext", referenced from:
      _secp256k1_num_mod_inverse in secp256.cgo2.o
  "___gmpn_get_str", referenced from:
      _secp256k1_num_get_bin in secp256.cgo2.o
  "___gmpn_mul", referenced from:
      _secp256k1_num_mul in secp256.cgo2.o
  "___gmpn_rshift", referenced from:
      _secp256k1_start in secp256.cgo2.o
      _secp256k1_ecmult_gen in secp256.cgo2.o
      _secp256k1_ecmult in secp256.cgo2.o
      _secp256k1_ecmult_wnaf in secp256.cgo2.o
  "___gmpn_set_str", referenced from:
      _secp256k1_start in secp256.cgo2.o
      _secp256k1_ecdsa_verify in secp256.cgo2.o
      _secp256k1_num_set_bin in secp256.cgo2.o
      _secp256k1_ecdsa_sign in secp256.cgo2.o
      _secp256k1_ecdsa_sig_sign in secp256.cgo2.o
      _secp256k1_ecdsa_sign_compact in secp256.cgo2.o
      _secp256k1_ecdsa_recover_compact in secp256.cgo2.o
      ...
  "___gmpn_sub_n", referenced from:
      _secp256k1_num_mod in secp256.cgo2.o
      _secp256k1_num_subadd in secp256.cgo2.o
      _secp256k1_num_mod_inverse in secp256.cgo2.o
  "___gmpn_tdiv_qr", referenced from:
      _secp256k1_num_mod in secp256.cgo2.o
      _secp256k1_num_div in secp256.cgo2.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ebuchman** [comment]
can you give us the output of `uname -a` at the terminal please?

**Comment by compleatang** [comment]
This is a very strange error. The `secp256` library is the core cryptographic primitives library we use. It is a bit funky, but this is something we've never seen before.

**Comment by androlo** [comment]
are you using 32 bit go?

**Comment by rajatmohanty** [comment]
Thanks everyone for reply, i checked my go version
$ go version
go version go1.4.1 darwin/386

Now i upgraded it to below & it fixed the thing
$ go version
go version go1.4.2 darwin/amd64

**Comment by compleatang** [comment]
Definitely. That is actually in production pipeline now.
