### ISSUE TITLE
Failed to add file: error message in helloworld sample application.

### ISSUE THREAD

**Issue by rajatmohanty** [eris-ltd/decerver#109]
Currently i am following Decerver Tutorial (https://decerver.io/tutorials/) and able to proceed
but when i am trying to add file operation in my browser, it is throwing me an error message "Failed to add file: Internal error: failed to read file"

Steps followed for this -

$ export GOPATH=$HOME/gocode
$ export PATH=$PATH:$GOPATH/bin
$ go get github.com/eris-ltd/decerver/cmd/decerver
$ go install github.com/eris-ltd/decerver/cmd/decerver
$ go get github.com/eris-ltd/epm-go/cmd/epm
$ go install github.com/eris-ltd/epm-go/cmd/epm
$ cd ~/.decerver/dapps/
$ git clone https://github.com/eris-ltd/hello-world-dapp.git helloworld
Cloning into 'helloworld'...
remote: Counting objects: 227, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 227 (delta 6), reused 0 (delta 0), pack-reused 192
Receiving objects: 100% (227/227), 61.80 KiB | 0 bytes/s, done.
Resolving deltas: 100% (72/72), done.
Checking connectivity... done.
01hw605249:dapps administrator$ cd helloworld/contracts
01hw605249:contracts administrator$ epm new -type thel -name helloworld -checkout

-----------------------

{
        "address": "0000000000THISISDOUG",
        "pdx": "",
        "doug": "",
        "unique": false,
        "private-key": "",
        "model": "",
        "no-gendoug": true,
        "consensus": "",
        "difficulty": 15,
        "public:mine": 0,
        "public:create": 0,
        "public:tx": 0,
        "maxgastx": "",
        "tapow": 0,
        "blocktime": 0,
        "vm": null,
        "accounts": [
                {
                        "address": "0xbbbd0256041f7aed3ce278c56ee61492de96d001",
                        "name": "",
                        "balance": "1000000000000000000000000000000000000",
                        "permissions": null,
                        "stake": 0
                }
        ]
}
------------------------
01hw605249:contracts administrator$ epm head
thelonious/f858469a00e80e4f5eb536501eb7d98c7e1cc432
01hw605249:contracts administrator$ epm refs
Name:   helloworld          
Chain: thelonious/f858469a00e80e4f5eb536501eb7d98c7e1cc432                                                                      
Address: 796ef3c8a245c3c02ae3c771c8a0159b64122200
------------------------
01hw605249:contracts administrator$ epm -log 2 deploy helloworld.pdx
2015/03/12 16:04:01 [EPM-CLI] There was no test found for package-definition helloworld. Deploying without test ...
2015/03/12 16:04:01 [EPM] Executing job: deploy	args: ["./test.lll" {{ROOT}}]
2015/03/12 16:04:01 [EPM] Deployed 798e42f58430676472df7d10691bf23cb042f1cf as 0x0f7e5921752c1138801f17036e1759180ba335c9
------------------------
blockchain_id : f858469a00e80e4f5eb536501eb7d98c7e1cc432
root_contract : 0x798e42f58430676472df7d10691bf23cb042f1cf
------------------------
cd ../
vi package.json
Now updated both blockchain_id & root_contract in package.json
------------------------
Go to decerver executable path & run it

$ cd /Users/administrator/gocode/bin
$ ./decerver
-------------------------
[Decerver Core] 2015/03/12 17:34:15 Starting decerver bootstrapping sequence.
[Decerver Core] 2015/03/12 17:34:15 Registering module 'ipfs'.
[Decerver Core] 2015/03/12 17:34:15 Registering module 'lmd'.
[Decerver Core] 2015/03/12 17:34:15 Registering module 'monk'.
[Dapp Manager] 2015/03/12 17:34:15 Registering dapps
[Dapp Manager] 2015/03/12 17:34:15 ## Registering dapp: Hello World ##
[Dapp Manager] 2015/03/12 17:34:15 Loaded javascript file 'DappHttpAPI.js'
[Dapp Manager] 2015/03/12 17:34:15 Loaded javascript file 'HelloWorld.js'
Registering path: helloworld/(.*)
[Dapp Manager] 2015/03/12 17:34:15 Done registering dapps.
[Decerver Core] 2015/03/12 17:34:15 Server started.
[Decerver Core] 2015/03/12 17:34:15 Running...
[martini] listening on localhost:3000 (development)
Loading module: monk
Loading module: ipfs
Loading module: lmd
----------------------------
Open another Terminal-2

$ curl http://localhost:3000/admin/switch/helloworld
Now Log in Terminal-1
[martini] Started GET /admin/switch/helloworld for 127.0.0.1:51273
Url: /admin/switch/helloworld
[Webserver] 2015/03/12 17:35:27 Switching to dapp:  helloworld
[Dapp Manager] 2015/03/12 17:35:27 Loading dapp: helloworld
[ScriptEngine] 2015/03/12 17:35:27 Core script loaded.
[ScriptEngine] 2015/03/12 17:35:27 Networking script loaded.
[ScriptEngine] 2015/03/12 17:35:27 Event processing script loaded.
[ScriptEngine] 2015/03/12 17:35:27 Js utilities script loaded.
[ScriptEngine] 2015/03/12 17:35:27 Creating new runtime: helloworld
[ScriptEngine] 2015/03/12 17:35:27 Runtimes: map[helloworld:0xc208136c40]
2015/03/12 17:35:27 [MONK] Identity created
2015/03/12 17:35:27 [CHAIN] Found genesis block
2015/03/12 17:35:27 [CHAIN] Last block (#4) 3450128a8dd0d1e641c40004577ad429b3a760b47d7eb7c2cea1634986f7dcc9
2015/03/12 17:35:27 [CHAIN] ChainID (f858469a00e80e4f5eb536501eb7d98c7e1cc432) 
2015/03/12 17:35:27 [CHAIN] Genesis (bed1bf5c2b2729e21bb1add1c4025bd19047be0b41385bc7385f2c92cf6dccb1) 
2015/03/12 17:35:27 [CHAIN] Updating checkpoint block: (#0) bed1bf5c2b2729e21bb1add1c4025bd19047be0b41385bc7385f2c92cf6dccb1
2015/03/12 17:35:27 [MONK] Created thelonious node
2015/03/12 17:35:27 [REACTOR] added new subscription to chainReady
2015/03/12 17:35:27 [REACTOR] started
2015/03/12 17:35:27 [REACTOR] added new subscription to chainReady
2015/03/12 17:35:27 [SERV] Ready and accepting connections
2015/03/12 17:35:27 [SERV] Server started
2015/03/12 17:35:27 [SERV] Connecting to peer: 111.111.111.111:9999
2015/03/12 17:35:27 [SERV] Peer handling started
2015/03/12 17:35:27 [REACTOR] added new subscription to newBlock
2015/03/12 17:35:27 [REACTOR] added new subscription to newBlock
2015/03/12 17:35:27 [REACTOR] added new subscription to messages
2015/03/12 17:35:27 [REACTOR] subscribing channel 1 to event chainReady blocked. skipping
[Dapp Manager] 2015/03/12 17:35:27 Root contract: 0x798e42f58430676472df7d10691bf23cb042f1cf
[Runtime] 2015/03/12 17:35:27 Creating helloworld.
[Runtime] 2015/03/12 17:35:27 Starting helloworld.
[martini] Completed 200 OK in 170.64869ms
2015/03/12 17:35:27 [REACTOR] removed subscription to chainReady
--------------------

Open Browser with below URL

http://localhost:3000/helloworld/

----------------------

Add File Operation

Name : john
Data : leopard
Press Submit option

Now an browser alert is showing me
The page at localhost:3000 says:
Failed to add file:
Internal error: failed to read file

Now Log in Terminal-1

[martini] Started GET /helloworld for 127.0.0.1:51280
[martini] Completed 302 Found in 217.873µs
[martini] Started GET /helloworld/ for 127.0.0.1:51280
[martini] [Static] Serving /helloworld/index.html
[martini] Completed 304 Not Modified in 242.243µs
[martini] Started GET /helloworld/js/helloworld.js for 127.0.0.1:51280
[martini] [Static] Serving /helloworld/js/helloworld.js
[martini] Completed 304 Not Modified in 195.84µs
2015/03/12 17:36:57 [PEER] Connection to peer failed. Giving up.dial tcp 111.111.111.111:9999: i/o timeout
[martini] Started POST /apis/helloworld/files for 127.0.0.1:51280
Stuff
URL /apis/helloworld/files
REQUEST: {"URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/apis/helloworld/files","RawQuery":"","Fragment":""},"Method":"POST","Host":"localhost:3000","Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["en-US,en;q=0.8"],"Connection":["keep-alive"],"Content-Length":["32"],"Content-Type":["text/plain;charset=UTF-8"],"Origin":["http://localhost:3000"],"Referer":["http://localhost:3000/helloworld/"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36"]},"Body":"{\"name\":\"john\",\"data\":\"leopard\"}"}
[Runtime] 2015/03/12 17:38:36 URLOBJ: map[path:[files] options:map[] error:]
[Runtime] 2015/03/12 17:38:36 Working
[Runtime] 2015/03/12 17:38:36 BODYOBJ: map[data:leopard name:john]
POSTing
Error finalizing POST: Post http://localhost:8080/ipfs/: dial tcp 127.0.0.1:8080: connection refused
[Runtime] 2015/03/12 17:38:36 Json string of resp obj:
{"Body":"Internal error: failed to read file","Header":{},"Status":500}
[Webserver] 2015/03/12 17:38:36 Response status message: 500
[Webserver] 2015/03/12 17:38:36 Response header stuff: map[]
[martini] Completed 500 Internal Server Error in 3.391298ms

-----------------
For Get File also i am getting an error message "file not found"

[martini] Started GET /apis/helloworld/files/john for 127.0.0.1:51386
Stuff
URL /apis/helloworld/files/john
REQUEST: {"URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/apis/helloworld/files/john","RawQuery":"","Fragment":""},"Method":"GET","Host":"localhost:3000","Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate, sdch"],"Accept-Language":["en-US,en;q=0.8"],"Connection":["keep-alive"],"Referer":["http://localhost:3000/helloworld/"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36"]},"Body":""}
[Runtime] 2015/03/12 17:45:56 URLOBJ: map[error: path:[files john] options:map[]]
[Runtime] 2015/03/12 17:45:56 Getting the storage for filename:0x000000000000000000000000000000000000000000000000000000006a6f686e
[Runtime] 2015/03/12 17:45:56 Hash: 0x0
[Runtime] 2015/03/12 17:45:56 File data: 
[Runtime] 2015/03/12 17:45:56 Json string of resp obj:
{"Body":"File not found: john","Header":{},"Status":404}
[Webserver] 2015/03/12 17:45:56 Response status message: 404
[Webserver] 2015/03/12 17:45:56 Response header stuff: map[]
[martini] Completed 404 Not Found in 44.40547ms

**Comment by androlo** [comment]
IPFS is not running. This is something that must be updated. Basically it is all fine, except the IPFS file store program is not running. 

The easiest way to do this is probably to use docker, the other way is to get and install [go-ipfs](ttps://github.com/jbenet/go-ipfs), then run `ipfs daemon -writable`. Basically `go get github.com/jbenet/go-ipfs` then cd to `go/src/github.com/go-ipfs/cmd/ipfs` and run `go install`, then run `ipfs init`, from any dir, which should generate a key for you.

This is weird to have to do just to run hello world, but we're setting up docker containers that links everything together.

**Comment by androlo** [comment]
Basically you will only have to run the docker file for hello-world, or any other dapp later, and it'll ensure that decerver and thelonious and ipfs and all of that is started up properly.

**Comment by androlo** [comment]
Actually both docker files and fig.yml files are in the hello world repo i see now. sorry. disregard the above.

**Comment by rajatmohanty** [comment]
@androlo thanks for reply, i have generate the key as you have mentioned.

01hw605249:~ administrator$ go get -u github.com/jbenet/go-ipfs/cmd/ipfs
01hw605249:~ administrator$ cd /Users/administrator/gocode/src/github.com/jbenet/go-ipfs/cmd/ipfs 
01hw605249:ipfs administrator$ go install
01hw605249:ipfs administrator$ ipfs init
initializing ipfs node at /Users/administrator/.go-ipfs
generating 4096-bit RSA keypair...done
peer identity: QmVCeLGMnbvZymdWKeaSMn7JKSQTefUdDpkms7DzBMzqxG
to get started, enter:

	ipfs cat /ipfs/QmV9E5oNhFDWeRV8NQ91G7vp3pvff2S4UYkn89T5koSzqo/readme

Now where i have to use this key ?

**Comment by rajatmohanty** [comment]
Oooh finally got it, my mistake i have to do 

$ ipfs daemon -writable
 
It fixed the thing :) 

Just a question does decerver has block chain technology module(thelonious) integrated or how can i use thelonious module in this helloworld application.

Perhaps i am bit new to this technology, hope you can reply my query. Thanks for your reply.

**Comment by compleatang** [comment]
Its a good question. At this point the decerver has thelonious (and ethereum) integrated into the decerver. So when you `go install` or `go build` decerver it will install both thelonious and ethereum as part of the decerver.

We are in the process of putting together our decerver and thelonious 0.9.0 sequence. In this sequence we are moving the blockchain modules out from the decerver as it has proved too restrictive for our development process. Effectively it will work similarly to how the decerver is working with ipfs at this point, namely via a well defined API which links the decerver's middlewear to the low level modules' functionality. 

We will be transparent as to how and when these changes get made, and there will be a transitional period in which both ways will work to ensure the most backward compatibility we can.

The result will be a system which will have slightly increased complexity but greatly improved resiliency and separation of concerns. To handle the complexity we are encouraging dapp devs to use groupings of docker containers via [docker-compose](https://docs.docker.com/compose/) which in our estimation will be an easy and straight forward way to handle the complexity of both the development process and usage. For an example of how this would look see the readme to our [2gather project](https://github.com/eris-ltd/2gather).

Am going to close since it appears the issue was solved, but if you have any other issues please do not hesitate to reopen and/or open a new issue! If you need any chat based help we are nearly always available on #erisindustries on Freenode.
