### ISSUE TITLE
Android support generally

### ISSUE THREAD

**Issue by ghost** [eris-ltd/decerver#110]
Irc user Mooseboobs talking about this, wanting to know where we're at. @compleatang

**Comment by compleatang** [comment]
Great question, although that question is more appropriately located in Thelonious. We are very interested in supporting Android and (eventually) iOS devices. Our focus at this point is in providing a stable platform for linux devices generally. 

That said, we would welcome community assistance in making Thelonious available as an Android lib. As was noted on IRC, the main external dependency is GMP which is necessary for the cryptographic primitives library that we use. If the ARM compatible lib [noted on IRC](https://github.com/Rupan/gmp) is truly workable, then it is conceivable that given [Golang's workability with Android](https://github.com/golang/mobile) it could actually work. 

As @androlo (who's suddenly become FradPickelton :neckbeard: ) noted, we would love this, but as a small team we need to keep our own focus on providing the base layer with straight linux compatibility.

**Comment by jarradh** [comment]
I'll take a crack at it then

**Comment by compleatang** [comment]
Would love that! :dancers:
