### ISSUE TITLE
DApps not registering if symlinked

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/decerver#80]
Especially for monkadmin we should be able to follow symlinks up -- for now.

There may be some security precautions to account for, but this also will be helpful for developers (e.g., dev somewhere else on your ~ and then symlink the root of the DApp in development back to ~/.decerver/dapps)

**Comment by androlo** [comment]
hmm this had something to do with serving dapps, didn't it? sounds like this would involve patching martini with weird platform-dependent code. this will be solved anyways, either with docker or with auto dapp-loading. please anyone open if there are real objections to this.
