### ISSUE TITLE
Module loading

### ISSUE THREAD

**Issue by androlo** [eris-ltd/decerver#86]
Thinking about how modules can be loaded. Actually this is something I've been welcoming since we got started, because of how simple it makes things.

If we open up outbound http from ate we could make this easy. we'd just program in a ZMQ socket in each one. We have to wrap modules anyways so this is not very different. Then, on the decerver end, we could have a javascript version of the API that calls them by using some bound ZMQ functions instead of calling directly (my ESRPC protocol could maybe be useful here). This means fully dynamic module loading and epm/decerver could both use the modules.

Modules could be packaged in a way similart to how we package dapps. It would have an executable, a package.json, and the javascript. Loading would be done the same way too (or the way we plan on implementing it for dapps), by hashing the files and making sure they're the right ones. 

There would of course be some security issues etc., like how do we know a module endpoint is what it claims to be, but we could work those out.

This means it could be loaded based on what the dapps need. It could even have multiple versions of the same module, and we don't have to worry about some weird go dynamic loading weirdness. It could even check a remote for the module if it is not find it locally. Also, it would be language agnostic. A module could be written in any language, though personally I'd recommend only using languages with compilers that produce proper stand-alone executables.

Hans approved.

**Comment by androlo** [comment]
This sounds better and better the more i think about it. I know this has been proposed so I'm assuming others are thinking along the same lines. It would not really have to be ZMQ all the time, since people could just do http if they have a simple module with no need for 2 way communication (like legal markdown for example). That's up to the implementor, since they decide whats on both ends (just like with dapps). ZMQ would be an alternative though, and part of the decerver.

This also would not change anything for dapp makers. The already existing javsacript apis (monk, ipfs, etc.) would not have to change. Its just a matter of what happens inside the functions.

ZMQ along with martini, ipfs, ethereum, thelonious, we'd add another layer of awesomeness to an already awesome stack. This is begging to be done.

**Comment by compleatang** [comment]
My feelings on ZMQ are well known...! :)

This also could allow modules to be local or on remote easier than our current loading and module sequence, which will be important when we start moving toward Decerver clusters.

**Comment by androlo** [comment]
Yes I know that. And after reading that document i share them too. This current system is so clunky. 

This system would also solves the "opening up networking" issue, like how do you limit certain js libraries to do certain calls. We could just add a lock so that outbound calls can only be to local, and then the module does the communication over the interwebs. That way you must approve outbound calls by validating the module that does them (like a firewall exception pretty much). And we can of course make it possible to do non local stuff too if that's wanted, with extra authentication and whatnot. Decerver will have a built in firewall.

**Comment by compleatang** [comment]
... thereby bringing a new level of sumptuous to Decerver. 

:+1:

**Comment by ebuchman** [comment]
Yes I support this design. Only thing is we also need a god-process to manage actually starting the different modules. Could be in process with decerver, or talk to it over zmq too. I think once we have the new master and some solid dapps we could start working towards this approach.

**Comment by compleatang** [comment]
god_process == docker-compose. this will get done another way :)
