### ISSUE TITLE
Readme - role of project unclear

### ISSUE THREAD

**Issue by kumavis** [eris-ltd/decerver#89]
I'm fairly familiar with ethereum and I can't figure out what this actually does by reading the README.
Theres plenty of excitement and buzz words, but how does this piece fit into the rest of the puzzle?
Making that clearer in the README would make the project stronger.

**Comment by dennismckinnon** [comment]
the decerver is essentially a web application server designed to make decentralized technologies and interaction between them simpler. Applications of this form are typically called dapps. The goal of the decerver is to make dapp making simpler, and dapp usage easier. Currently you can script interaction of a dapp with ethereum, our own eth-like smart contracts chain design thelonious, bitcoin (either through btcd or blockchain.info api), IPFS (a decentralized filestore), and Legal markdown. More modules are planned to be added. If you want something in particular you and PR a wrapper for it. We will be making the module creation process easier in the coming weeks.

Thanks for your interest and we will make sure to clarify the README.

**Comment by kumavis** [comment]
so this is a centralized server that has a scripting engine and exposes and api to interact with blockchains. correct?

**Comment by dennismckinnon** [comment]
no. The decerver is intended to server to localhost only. It stays in sync with other decervers through the decentralized protocols and is intended to be run locally.

**Comment by kumavis** [comment]
so this is a node for interacting with blockchains.

**Comment by kumavis** [comment]
and other decentralized protocols

**Comment by dennismckinnon** [comment]
yes that would be an adequate description. I would have started there, but did not know your background sorry. If you would like to know more decerver.io has more info. And/or you can join us on irc #erisindustries on freenode.

**Comment by kumavis** [comment]
cool thanks, that cleared things up.
I would recomend using READMEs for a more technical audience and just add a link to marketing and buzz.
I'll keep my eye on you guys.

**Comment by androlo** [comment]
point taken

**Comment by androlo** [comment]
re-opening.

There's more coming btw. There are people working on deployment, tutorials, automated tests, docker,  all manner of things. It will become a lot easier to get started.

**Comment by androlo** [comment]
I've added some more info in the README.md file. It is currently in the dev branch only, but we're merging today so it'll be on master as well. It's far from finished, but the approach now is to explain the different components of the decerver more precisely, and also use the hello world 1 dapp as an example of how applications actually run on the system.

I still need to add more context, like "what is the difference between decerver and decerver-client", or more generally - where does the decerver fit in to the Eris ecosystem as a whole. Then of course I need to add example code, more links, improve spelling etc., and also add more stuff about how dapps are loaded and unloaded etc., but I will do that continously.

**Comment by kumavis** [comment]
nice! looks much better

**Comment by androlo** [comment]
documentation will improve continously, closing this one.
