### ISSUE TITLE
Require command

### ISSUE THREAD

**Issue by androlo** [eris-ltd/decerver#93]
As per Caseys suggestion, we would load functionality into a js runtime by using a 'require' function. This would allow external libraries to be loaded into a dapp. Hopefully, if we switch to js module wrappers, we could load those using the same command. A backend js file could look something like this:

``` javascript
var events = require('events');
var websock = require('ws');
var monk = require('monk');

```

Not sure how it would work exactly, but making all include libs and decerver-modules into javascript modules seems like a good way of doing things, and generally to mimic the node.js system as much as possible.

**Comment by androlo** [comment]
There is already functions in the runtime object to load scripts by path btw. It could simply be bound and extended any way we need it. I could literally have a basic form of this command done in 15 minutes. To handle modules later and stuff, I think we'll have to do something a bit more sophisticated, as they require startup etc. Perhaps just start them when required, and block to begin with (otto not really good with async atm.). We would have to consider cleanup as well.

**Comment by compleatang** [comment]
:+1:

One thing we should take into consideration is that from the DApp root, we should be able to scan `node_modules` folder before loading along with `models` folder. This would make it easy to `npm install` from the DApp root folder using the `package.json` and normal npm. That path would also let us use npm for packaging and distribution of Ate compatible packages even though they cannot be run in node directly.

**Comment by androlo** [comment]
ooh nice.. that's super useful.

**Comment by compleatang** [comment]
deprecated in favor of new design paradigm.
