### ISSUE TITLE
decerver init

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/decerver#97]
set up all the proper files, also should call epm init since its wrapped. that will get everything set up for further sumptuous actions.

**Comment by ebuchman** [comment]
@changetip @compleatang have a hug

**Comment by changetip** [comment]
Hi @compleatang, @ebuchman sent you a Bitcoin tip worth a hug (3,258 bits/$0.75), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/404383)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by compleatang** [comment]
deprecated.
